site_name: Prefeitura de Concórdia
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Grupo01
edit_uri: ""

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: "index.md"
  - Planejamento:
    - Escolha do Site: "planejamento/escolhaSite.md"
    - Metodologias e Processos: "planejamento/documentoDeMetodologia.md"
    - Processo de Design: "planejamento/processoDeDesign.md"
    - Ferramentas: "planejamento/ferramentas.md"
    - Heatmap e Cronogramas: "planejamento/cronograma.md"
  - Análise de Requisitos:
    - Perfil de Usuário:
      - Questionário e Perfis de Usuários: "analiseRequisitos/questionarioEPerfil.md"
      - Personas: "analiseRequisitos/personas.md"
      - Entrevista: "analiseRequisitos/entrevista.md"
    - Metas de Usabilidade: "analiseRequisitos/metasUsabilidade.md"
  - Análise de Tarefas:
    - Árvores de Tarefas Concorrentes CTT: "analiseTarefas/ctt.md"
    - Análise de Tarefa KLM: "analiseTarefas/klm.md"
    - Análise Hierárquica de Tarefa HTA: "analiseTarefas/hta.md"
    - Análise de Tarefa CMN: "analiseTarefas/cmn.md"
  - Apresentações:
    - Ponto de Controle 1: "apresentacoes/p1.md"
    - Ponto de Controle 2: "apresentacoes/p2.md"

markdown_extensions:
  - attr_list
