site_name: Prefeitura de Concórdia
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Grupo01
edit_uri: ""

theme:
  logo: images/brasaoPrefeitura.png
  favicon: images/brasaoPrefeituraFavicon.png
  features: navigation.tabs
  name: material
  palette:
    primary: green

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Planejamento:
    - Escolha do Site: "planejamento/escolhaSite.md"
    - Metodologias e Processos: "planejamento/documentoDeMetodologia.md"
    - Processo de Design: "planejamento/processoDeDesign.md"
    - Ferramentas: "planejamento/ferramentas.md"
    - Heatmap e Cronogramas: "planejamento/cronograma.md"
  - Análise de Requisitos:
    - Perfil de Usuário:
        - Questionário e Perfis de Usuários: "analiseRequisitos/questionarioEPerfil.md"
        - Personas: "analiseRequisitos/personas.md"
        - Entrevista: "analiseRequisitos/entrevista.md"
    - Principios e Diretrizes: "analiseRequisitos/principios_e_diretrizes.md"    
    - Guia de estilo: "analiseRequisitos/guiaDeEstilo.md"
    - Metas de Usabilidade: "analiseRequisitos/metasUsabilidade.md"
    - Características da Plataforma: "analiseRequisitos/caracteristicasDaPlatafoma.md"
  - Análise de Tarefas:
    - Árvores de Tarefas Concorrentes CTT: "analiseTarefas/ctt.md"
    - Análise de Tarefa KLM: "analiseTarefas/klm.md"
    - Análise Hierárquica de Tarefa HTA: "analiseTarefas/hta.md"
    - Análise de Tarefa CMN: "analiseTarefas/cmn.md"
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de tarefas:
        - Planejamento e Avaliação das Análises de Tarefas: "analiseTarefas/planejamentoAvaliacaoAnaliseTarefa.md"
      - Storyboards:
        - Storyboards: "nivel1/storyboards.md"
        - Planejamento e Avaliação dos Storyboards: "nivel1/planejamentoAvaliacaoStoryboard.md"
    - Nível 2:
      - Protótipo de Papel:
        - Protótipo de Papel: "nivel2/prototipo.md"
        - Planejamento de Avaliação: "nivel2/planejamento.md"
    - Nível 3:
      - Protótipo de Alta Fidelidade:
        - Planejamento de Avaliação: "nivel3/planejamento.md"
        - Protótipo de alta: "nivel3/prototipo.md"
  - Verificação:
    - Introdução: "verificacao/introducao.md"
    - Características da Plataforma: "verificacao/caracteristicas_da_plataforma.md"
    - Storyboards: "verificacao/storyboards.md"
    - Personas: "verificacao/personas.md"


  - Apresentações:
    - Ponto de Controle 1: "apresentacoes/p1.md"
    - Ponto de Controle 2: "apresentacoes/p2.md"
    - Ponto de Controle 3: "apresentacoes/p3.md"
    - Ponto de Controle 4: "apresentacoes/p4.md"
    - Ponto de Controle 5: "apresentacoes/p5.md"
    - Ponto de Controle 6: "apresentacoes/p6.md"

markdown_extensions:
  - attr_list
