site_name: IHC grupo 01
repo_url: https://github.com/Interacao-Humano-Computador/2021.1-Grupo01
edit_uri: ""

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: "index.md"
  - Planejamento:
    - Escolha do Site: "planejamento/escolhaSite.md"
    - Metodologias e Processos: "planejamento/documentoDeMetodologia.md"
    - Processo de Design: "planejamento/processoDeDesign.md"
    - Ferramentas: "planejamento/ferramentas.md"
    - Heatmap e Cronogramas: "planejamento/cronograma.md"
  - Apresentações:
    - Ponto de Controle 1: "apresentacoes/p1.md"
  - Analise de Tarefa:
    - Entrevista: "analise_de_requisitos/entrevista.md"

markdown_extensions:
  - attr_list
